name: Build Status

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install SVN
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Install dependencies
        run: npm install

      - name: Run lint checks
        run: npm run lint:js && npm run lint:css

      - name: Build plugin
        run: npm run build

      - name: Create plugin ZIP
        run: npm run plugin-zip
