name: Coding Standards & Compatibility Checks

on:
  push:
    branches:
      - trunk
      - anushka
  workflow_dispatch:

jobs:
  build:
    name: Run Coding Standards and Compatibility Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, json, curl
          coverage: none

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install NPM dependencies
        run: npm install

      - name: Run PHP Coding Standards (PHP_CodeSniffer)
        run: vendor/bin/phpcs

      - name: Run JS & CSS Lint
        run: npm run lint

      - name: Check PHP Compatibility
        run: vendor/bin/phpcs -p . --standard=PHPCompatibility --runtime-set testVersion 8.1
